#!/bin/bash
ipmitool -I lanplus -H ${1}ipmi -U ADMIN -f ~/RHEL6_Cluster/ipmi_password.txt chassis bootdev pxe
ipmitool -I lanplus -H ${1}ipmi -U ADMIN -f ~/RHEL6_Cluster/ipmi_password.txt power reset
